version: "3.9"
services:

  postgres:
    image: postgres:14.2
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one:1.31
    command: [ "--log-level=debug" ]
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"